[2023-10-04T18:09:49.332+0300] {processor.py:157} INFO - Started process (PID=14238) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:09:49.333+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:09:49.334+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:09:49.334+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:09:49.338+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:09:49.337+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:09:49.339+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:09:49.338+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:09:49.339+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:09:49.533+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.206 seconds
[2023-10-04T18:11:22.902+0300] {processor.py:157} INFO - Started process (PID=14755) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:11:22.904+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:11:22.905+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:11:22.904+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:11:22.909+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:11:22.908+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:11:22.909+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:11:22.909+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:11:22.910+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:11:22.923+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-04T18:14:09.991+0300] {processor.py:157} INFO - Started process (PID=16012) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:14:10.029+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:14:10.030+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:14:10.030+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:14:10.036+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:14:10.034+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:14:10.036+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:14:10.036+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:14:10.037+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:14:10.051+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-10-04T18:15:21.728+0300] {processor.py:157} INFO - Started process (PID=16098) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:15:21.749+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:15:21.750+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:15:21.750+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:15:21.756+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:15:21.754+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:15:21.756+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:15:21.756+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:15:21.757+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:15:21.771+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-10-04T18:16:13.819+0300] {processor.py:157} INFO - Started process (PID=16153) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:16:13.845+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:16:13.846+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:16:13.846+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:16:13.851+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:16:13.849+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:16:13.851+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:16:13.851+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:16:13.851+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:16:13.866+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-10-04T18:17:41.817+0300] {processor.py:157} INFO - Started process (PID=16260) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:17:41.847+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T18:17:41.848+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:17:41.848+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:17:41.853+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:17:41.852+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T18:17:41.854+0300] {logging_mixin.py:149} INFO - [2023-10-04T18:17:41.854+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T18:17:41.854+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T18:17:41.869+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2023-10-04T21:00:49.428+0300] {processor.py:157} INFO - Started process (PID=22442) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:00:49.430+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:00:49.431+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:00:49.431+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:00:49.436+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:00:49.434+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:00:49.436+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:00:49.436+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:00:49.436+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:00:49.450+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-04T21:02:04.945+0300] {processor.py:157} INFO - Started process (PID=22637) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:04.946+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:02:04.948+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:04.947+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:04.952+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:04.951+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:02:04.953+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:04.952+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:02:04.953+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:04.967+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-04T21:02:59.847+0300] {processor.py:157} INFO - Started process (PID=22688) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:59.849+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:02:59.850+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:59.849+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:59.854+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:59.853+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:02:59.855+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:02:59.855+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:02:59.855+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:02:59.869+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-04T21:03:56.743+0300] {processor.py:157} INFO - Started process (PID=22739) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:03:56.759+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:03:56.760+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:03:56.760+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:03:56.765+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:03:56.764+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:03:56.766+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:03:56.766+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:03:56.766+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:03:56.781+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-10-04T21:04:54.519+0300] {processor.py:157} INFO - Started process (PID=22813) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:04:54.520+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:04:54.521+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:04:54.521+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:04:54.524+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:04:54.523+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:04:54.525+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:04:54.525+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:04:54.525+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:04:54.536+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-10-04T21:05:50.645+0300] {processor.py:157} INFO - Started process (PID=22890) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:05:50.647+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:05:50.648+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:05:50.648+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:05:50.653+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:05:50.651+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:05:50.653+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:05:50.653+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:05:50.654+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:05:50.669+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-10-04T21:06:48.880+0300] {processor.py:157} INFO - Started process (PID=22942) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:06:48.881+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:06:48.882+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:06:48.882+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:06:48.887+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:06:48.885+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:06:48.887+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:06:48.887+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:06:48.888+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:06:48.902+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-10-04T21:07:39.441+0300] {processor.py:157} INFO - Started process (PID=22990) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:07:39.442+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:07:39.443+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:07:39.443+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:07:39.448+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:07:39.447+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:07:39.449+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:07:39.449+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:07:39.449+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:07:39.463+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-10-04T21:08:28.438+0300] {processor.py:157} INFO - Started process (PID=23054) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:08:28.439+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:08:28.440+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:08:28.439+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:08:28.443+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:08:28.442+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:08:28.444+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:08:28.444+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:08:28.444+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:08:28.456+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-10-04T21:09:17.965+0300] {processor.py:157} INFO - Started process (PID=23101) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:09:17.966+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:09:17.967+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:09:17.967+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:09:17.972+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:09:17.970+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:09:17.972+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:09:17.972+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:09:17.973+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:09:17.986+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-10-04T21:10:08.852+0300] {processor.py:157} INFO - Started process (PID=23209) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:10:08.862+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:10:08.863+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:10:08.862+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:10:08.867+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:10:08.866+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:10:08.868+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:10:08.867+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:10:08.868+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:10:08.882+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-10-04T21:52:14.716+0300] {processor.py:157} INFO - Started process (PID=26951) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:52:14.741+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:52:14.742+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:52:14.742+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:52:14.747+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:52:14.746+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:52:14.748+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:52:14.748+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:52:14.748+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:52:14.763+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-10-04T21:53:12.753+0300] {processor.py:157} INFO - Started process (PID=27049) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:53:12.754+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:53:12.755+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:53:12.755+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:53:12.760+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:53:12.759+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:53:12.761+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:53:12.760+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:53:12.761+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:53:12.775+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-10-04T21:54:16.545+0300] {processor.py:157} INFO - Started process (PID=27130) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:54:16.547+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:54:16.548+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:54:16.548+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:54:16.553+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:54:16.551+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:54:16.553+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:54:16.553+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:54:16.553+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:54:16.569+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-10-04T21:55:12.156+0300] {processor.py:157} INFO - Started process (PID=27205) to work on /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:55:12.158+0300] {processor.py:826} INFO - Processing file /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-04T21:55:12.159+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:55:12.159+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:55:12.164+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:55:12.162+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-04T21:55:12.164+0300] {logging_mixin.py:149} INFO - [2023-10-04T21:55:12.164+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-04T21:55:12.165+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-04T21:55:12.178+0300] {processor.py:179} INFO - Processing /home/paulet/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
